title = "sympasium"
baseURL = "https://sympasium.org/"
languageCode = "fr"
theme = "airspace-hugo"

[menu]

  # [[menu.header]]
  #   weight = 2
  #   name = "Work"
  #   url = "/work"
  # [[menu.header]]
  #   weight = 3
  #   name = "Blog"
  #   url = "/blog"
  # [[menu.header]]
  #   weight = 4
  #   name = "Service"
  #   url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  # [[menu.footer]]
  #   weight = 1
  #   name = "About us"
  #   url = "#"
  # [[menu.footer]]
  #   weight = 2
  #   name = "Contact us"
  #   url = "#"
  # [[menu.footer]]
  #   weight = 3
  #   name = "How it works"
  #   url = "#"
  # [[menu.footer]]
  #   weight = 4
  #   name = "Blog"
  #   url = "#"
  # [[menu.footer]]
  #   weight = 5
  #   name = "Terms"
  #   url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  date_format = "6 January 2006"

  home = "Accueil"

  [params.slider]
    enable = true
    title = "Une rencontre<br>des indépendants<br>par les indépendants"
    subtitle = ""

  [params.wrapper]
    enable = true
    title = "sympasium"
    italic = "\"Il n'y a pas de plaisir comparable à celui de rencontrer un vieil ami, excepté peut-être celui d'en faire un nouveau.\"<br/><strong>Rudyard Kipling</strong>"
    paragraph = "En plein coeur de l'été, sympasium propose un nouveau format de rencontre pour les indépendants.<br>Sympasium se déroule toute une semaine dans un petit coin de paradis, le cadre idéal pour passer de bons moments. Au programme : réseautage, sport, débats, fêtes et bien plus encore."

  [params.blog]
    enable = false
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "L'indépendance comme force"
    content = "Dans notre monde où le travail est morcelé et souvent solitaire, un sympasium est un assemblage de bon-temps, discussions, activités, apprentissage…<br>Nous croyons au partage des expériences et à la diversité des points de vue comme enrichissement, aux amitiés nouvelles pour développer de futures collaborations."
    # [params.feature.button]
    #   caption = "View Works"
    #   url = "#"

  [params.call]
    enable = true
    title = "Inscrivez-vous vite !"
    paragraph = ""
    [params.call.button]
      text = "Contactez nous"
      url = "/contact"

  [params.contact]
    enable = true
    title = "Contactez nous"
    subtitle = "Ne soyez pas timide ;)"
    [params.contact.form]
      name = "Votre nom"
      email = "Votre courriel"
      subject = "Sujet"
      message = "Votre gentil message"
      button = "Envoyer le message"
    # [params.contact.box]
    #   title = "Stop by for a visit"
    #   address = "North Main Street, Brooklyn Australia"
    #   email = "Email: contact@mail.com"
    #   phone = "Phone: +88 01672 506 744"
    # [params.contact.gmaps]
    #   title = "We Also Count in Google Maps"
